config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :password_resets
  resources :log, only: [:index] 
  root 'sessions#new'

  resources :transactions do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  scope :sorted, -> { order('id ASC') }
end

app/models/log.rb
# frozen_string_literal: true

class Log < ApplicationRecord
  scope :sorted, -> { order('id DESC') }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  scope :sorted, -> { order('id DESC') }
  validates_presence_of  :requestor_name, :requestor_email, :item_name, :item_quantity
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates_presence_of :name
  validates_uniqueness_of :email
  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    loop do
      self[column] = SecureRandom.urlsafe_base64
      break unless User.exists?(column => self[column])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to root_url, alert: 'Not authorized' if current_user.nil?
  end
  helper_method :current_user
end

app/controllers/log_controller.rb
# frozen_string_literal: true

class LogController < ApplicationController
  def index
    @log = Log.sorted
    respond_to do |format|
    format.xlsx {
        response.headers[
            'Content-Disposition'
            ] = "attachment; filename='items.xlsx'"
          }
      format.html { render :index }
    end
  end

  def log_params
    params.require(:log).permit(:requestor_name, :requestor_email, :type_, :item_name, :item_quantity, :check_in)
  end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:email])
    @user&.send_password_reset
    redirect_to(root_url, notice: 'Email sent with password reset instuctions.')
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to(new_password_reset_path, alert: 'Password reset has expired.')
    elsif @user.update_attributes(user_params)
      redirect_to(root_url, notice: 'Password has been reset!')
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      session[:user_id] = user.id
      redirect_to(transactions_path, notice: 'Logged in!')
    else
      flash.now[:alert] = 'Email or password is invalid'
      render('new')
    end
  end

  def destroy
    cookies.delete(:auth_token)
    session[:user_id] = nil
    redirect_to(root_url, notice: 'Logged out!')
  end

  # <%= f.form_group do %>
  # <%= f.check_box :remember_me %>
  # <% end %>
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authorize, only: %i[create edit update delete destroy show new index]
  def index
    @transactions = Transaction.sorted

    
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    @log = Log.new
  end

  def create
    @transaction = Transaction.new(transaction_params) # need to find out how to set the 2 week immediately
    @transaction.type_ = 'Checked Out'

    @log = Log.new
    @log.id = @transaction.id
    @log.requestor_name = @transaction.requestor_name
    @log.requestor_email = @transaction.requestor_email
    @log.type_ = @transaction.type_
    @log.item_name = @transaction.item_name
    @log.item_quantity = @transaction.item_quantity
    @log.save

    if @transaction.save
      flash[:notice] = 'Transaction Created Successfully!'
      redirect_to(transactions_path)
    else
      render('new')
    end
  end

  # in this case, I am using edit/update as the "check in" form
  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @log = Log.find(params[:id])
    @log.type_ = 'Checked In'
    time = Time.new
    @log.check_in = Date.new(time.year, time.month, time.day)
    @log.save
    @transaction.type_ = 'Checked In' # hopefully updates the 'type_' attribute in table

    if @transaction.save
      flash[:notice] = "Check Out ID #'#{@transaction.id}' Checked In Successfully!"
      redirect_to(transaction_path(@transaction))
    else
      render('edit')
    end
  end

  # these bottom two probably should never be used, but I included the definitions here just in case
  def delete; end

  def destroy; end

  def transaction_params
    params.require(:transaction).permit(:requestor_name, :requestor_email, :type_, :item_name, :item_quantity, :remind_date)
  end

  def log_params
    params.require(:log).permit(:requestor_name, :requestor_email, :type_, :item_name, :item_quantity, :check_in)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(transactions_path, notice: 'Thank you for signing up!')
    else
      redirect_to(new_user_path, alert: 'Error creating user.')
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/log_helper.rb
# frozen_string_literal: true

module LogHelper
end

app/helpers/password_resets_helper.rb
# frozen_string_literal: true

module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/test_index_helper.rb
# frozen_string_literal: true

module TestIndexHelper
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "en">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <head>
    <title>SweItemCheckInOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
    <% if !flash[:notice].blank? %>
      <div class=notice>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if !flash[:alert].blank? %>
      <div class=alert>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if current_user %>
      Logged in as <%= current_user.name %>
      <%= link_to "Log Out", session_path("current"), method: "delete" %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", new_session_path %>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/log/index.html.erb
<h1>Transaction log</h1>

<%= link_to("<< Back to List", "transactions") %>

<%= link_to "Export to spreadsheet", log_index_path(format: "xlsx")%>

<table class="listing" summary="Transaction Log">
    <tr class="header">
        <th style="padding:0 15px 0 0;">Check Out ID</th>
        <th style="padding:0 15px 0 0;">Checked Out By</th>
        <th style="padding:0 15px 0 0;">Check Out Email</th>
        <th style="padding:0 15px 0 0;">Type</th>
        <th style="padding:0 15px 0 0;">Item Name</th>
        <th style="padding:0 15px 0 0;">Item Quantity</th>
        <th style="padding:0 15px 0 0;">Check in Date</th>
    </tr>
    <% @log.each do |t| %>
    <tr>
        <td style="padding:0 15px 0 0;"><%= t.id %></td>
        <td style="padding:0 15px 0 0;"><%= t.requestor_name %></td>
        <td style="padding:0 15px 0 0;"><%= t.requestor_email%></td>
        <td style="padding:0 15px 0 0;"><%= t.type_%></td>
        <td style="padding:0 15px 0 0;"><%= t.item_name%></td>
        <td style="padding:0 15px 0 0;"><%= t.item_quantity%></td>
        <td style="padding:0 15px 0 0;"><%= t.check_in%></td>
    </tr>
    <% end %>
</table>

app/views/password_resets/edit.html.erb
<div style="margin:auto;">
<h1> Reset Password </h1>
<%= bootstrap_form_for(@user, :url => password_reset_path(params[:id]), layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class = "field font-weight-bold">
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
    </div> 
      <%= f.submit "Update Password" %>
<% end %>
</div>

app/views/password_resets/new.html.erb
<div style="margin:auto;">
<h1>Reset Password</h1>
<%= bootstrap_form_tag(url: password_resets_path, :method => :post, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
    <div class="field font-weight-bold">
        <%= f.text_field :email %>
    </div>
    <%= f.submit "Reset Password" %>
<% end %>
</div>

app/views/test_index/index.html.erb
<h1>TestIndex#index</h1>
<p>Find me in app/views/test_index/index.html.erb</p>

<p>Below will be link where, after user logs in, will have option to go to check in/out page</p>
<%= link_to 'Check Item In/Out', transactions_index_path, class: "header" %>

app/views/transactions/delete.html.erb
<% if current_user %>
      Logged in as <%= current_user.name %>
      <%= link_to "Log Out", session_path("current"), method: "delete" %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", new_session_path %>
    <% end %>
<h1>Transactions#delete</h1>
<p>Find me in app/views/transactions/delete.html.erb</p>

app/views/transactions/edit.html.erb
<p><%= link_to("<< Back to List", transactions_path, :class => 'back-link') %></p>

<div class="subjects edit check in">

  <h1>Check In Item Confirmation Page!</h1>

  <%= form_for(@transaction) do |f| %>

  <p>Can you confirm that the item has been returned to its rightful place?</p>
  <p class="reference-name">Check Out ID #<%= @transaction.id %></p>

  <div class="form-buttons">
    <%= f.submit("Check In Item") %>
  </div>

  <% end %>
</div>

app/views/transactions/index.html.erb
<h1>Check In/Out</h1>

<%= link_to("Check Out Item", new_transaction_path, :class => "action new") %>
<%= link_to("View History", "log") %>


<table class="listing" summary="Transaction List">
    <tr class="header">
        <th>Check Out ID</th>
        <th>Checked Out By</th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Checkout date</th>
    </tr>
    <% @transactions.each do |t| %>
    <tr>
        <td><%= t.id %></td>
        <td><%= t.requestor_name %></td>
        <td><%= t.item_name %></td>
        <td><%= t.item_quantity %></td>
        <td><%= t.created_at %></td>
        <td><%= t.type_ %></td>
        <td class="actions">
            <%= link_to("View Details", transaction_path(t), :class => 'action show') %>
            <%= link_to("Check In", edit_transaction_path(t), :class => 'action edit') %>
        </td>
    </tr>
    <% end %>
</table>

app/views/transactions/new.html.erb
<p><%= link_to("<< Back to List", transactions_path, :class => 'back-link') %></p>

<div class="Transaction new">
  <h1>Create Transaction</h1>

  <%= form_for(@transaction, :url => transactions_path, :method => 'post') do |f| %>

  <table summary="Transaction form fields">
    <tr>
      <th>Requestor Name</th>
      <td><%= f.text_field(:requestor_name) %></td>
    </tr>
    <tr>
      <th>Requestor Email</th>
      <td><%= f.text_field(:requestor_email) %></td>
    </tr>
    <tr>
      <th>Item Name</th>
      <td><%= f.text_field(:item_name) %></td>
    </tr>
    <tr>
      <th>Quantity</th>
      <td><%= f.number_field(:item_quantity) %></td>
    </tr>
  </table>

  <div class="form-buttons">
    <%= f.submit("Check Out Item") %>
  </div>
  <% end %>
</div>

app/views/transactions/show.html.erb
<p><%= link_to("<< Back to All Check Out Items", transactions_path, :class => 'back-link') %></p>


<div class="transaction show">

  <h1>Show Check Out #<%=@transaction.id %> Details</h1>

  <table summary="transaction Detail view">
    <tr>
      <th>Check Out Person Name</th>
      <td><%= @transaction.requestor_name %></td>
    </tr>
    <tr>
      <th>Check Out Person Email</th>
      <td><%= @transaction.requestor_email %></td>
    </tr>
    <tr>
      <th>Item Check Out</th>
      <td><%= @transaction.item_name %></td>
    </tr>
    <tr>
      <th>Quantity Checked Out</th>
      <td><%= @transaction.item_quantity %></td>
    </tr>
    <tr>
      <th>Reminder To Return Date</th>
      <td><%= @transaction.remind_date %></td>
    </tr>
    <tr>
      <th>Checked Out On</th>
      <td><%= @transaction.created_at %></td>
    </tr>
    <tr>
      <th>Checked Out Status</th>
      <td><%= @transaction.type_ %></td>
    </tr>
  </table>
</div>

app/views/users/index.html.erb
<div style="margin:auto;">
<h1>Sign Up</h1>
<%= bootstrap_form_for(@user,:url => users_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
        <h2> Form is invalid </h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <div class = "field font-weight-bold">
    <%= f.text_field :name %>

    <%= f.text_field :email %>

    <%= f.password_field :password %>

    <%= f.password_field :password_confirmation %>
  </div>    

    <%= f.submit "Create User" %>
<% end %>
Already have an account? <%= link_to "Login", root_url %></p>
</div>

app/views/users/new.html.erb
<div style="margin:auto;">
<h1>Sign Up</h1>
<%= bootstrap_form_for(@user,:url => users_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
        <h2> Form is invalid </h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <div class = "field font-weight-bold">
    <%= f.text_field :name %>

    <%= f.text_field :email %>

    <%= f.password_field :password %>

    <%= f.password_field :password_confirmation %>
  </div>    

    <%= f.submit "Create User" %>
<% end %>
Already have an account? <%= link_to "Login", root_url %></p>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>